<h1>Register</h1>

<?php 
if(!$this->enableRegistration)
{
    print '<div class="alert alert-error">Registration is disabled</div>';
    return;
}

$form = $this->registerForm;

$form->prepare();
$form->setAttribute('action', $this->formAction);
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>

<dl class="zend_form">

<?php foreach ($form->getElements() as $element) { ?>
    <?php if ($element->getLabel()) { ?>
    <dt><?php echo $this->formLabel($element); ?></dt>
    <?php } ?>
    <dd><?php echo $this->formInput($element) . $this->formElementErrors($element); ?></dd>
<?php } ?>

</dl>
