<h1>Register</h1>

<?php 
if(!$this->enableRegistration) {
    print '<div class="alert alert-error">Registration is disabled</div>';
    return;
}

$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register/step2', array('token'=>$this->model->getRequestKey())));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if ($element->getName() == 'email') continue; /* Don't render the email element, as we've added it below as a hidden field */ ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
    <input type="hidden" name="email" value="<?php echo $this->escapeHtmlAttr($this->model->getEmailAddress()); ?>" />
<?php echo $this->form()->closeTag() ?>
