<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliTwoStageSignupTest\Service\EmailVerificationTest'              => __DIR__ . '/tests/CdliTwoStageSignupTest/Service/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Mapper\EmailVerificationTest'               => __DIR__ . '/tests/CdliTwoStageSignupTest/Mapper/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Model\EmailVerificationTest'                => __DIR__ . '/tests/CdliTwoStageSignupTest/Model/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Validator\AssertNoValidationInProgressTest' => __DIR__ . '/tests/CdliTwoStageSignupTest/Validator/AssertNoValidationInProgressTest.php',
    'CdliTwoStageSignupTest\Framework\TestCase'                         => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/TestCase.php',
    'CdliTwoStageSignupTest\Framework\TestCaseOptions'                  => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/TestCaseOptions.php',
    'CdliTwoStageSignupTest\Framework\MapperTestCase'                   => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/MapperTestCase.php',
    'CdliTwoStageSignupTest\ServiceConfigurationTest'                   => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/ServiceConfigurationTest.php',
    'CdliTwoStageSignup\Module'                                         => __DIR__ . '/Module.php',
    'CdliTwoStageSignup\Controller\RegisterController'                  => __DIR__ . '/src/CdliTwoStageSignup/Controller/RegisterController.php',
    'CdliTwoStageSignup\Service\EmailVerification'                      => __DIR__ . '/src/CdliTwoStageSignup/Service/EmailVerification.php',
    'CdliTwoStageSignup\Mapper\EmailVerification'                       => __DIR__ . '/src/CdliTwoStageSignup/Mapper/EmailVerification.php',
    'CdliTwoStageSignup\Model\EmailVerification'                        => __DIR__ . '/src/CdliTwoStageSignup/Model/EmailVerification.php',
    'CdliTwoStageSignup\Validator\AssertNoValidationInProgress'         => __DIR__ . '/src/CdliTwoStageSignup/Validator/AssertNoValidationInProgress.php',
    'CdliTwoStageSignup\Form\EmailVerification'                         => __DIR__ . '/src/CdliTwoStageSignup/Form/EmailVerification.php',
    'CdliTwoStageSignup\Form\EmailVerificationFilter'                   => __DIR__ . '/src/CdliTwoStageSignup/Form/EmailVerificationFilter.php',
);
