<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliTwoStageSignupTest\Framework\TestCase'                 => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/TestCase.php',
    'CdliTwoStageSignup\Module'                                 => __DIR__ . '/Module.php',
    'CdliTwoStageSignup\Controller\RegisterController'          => __DIR__ . '/src/CdliTwoStageSignup/Controller/RegisterController.php',
    'CdliTwoStageSignup\Service\EmailVerification'              => __DIR__ . '/src/CdliTwoStageSignup/Service/EmailVerification.php',
    'CdliTwoStageSignup\Model\EmailVerification'                => __DIR__ . '/src/CdliTwoStageSignup/Model/EmailVerification.php',
    'CdliTwoStageSignup\Model\EmailVerificationMapper'          => __DIR__ . '/src/CdliTwoStageSignup/Model/EmailVerificationMapper.php',
    'CdliTwoStageSignup\Validator\AssertNoValidationInProgress' => __DIR__ . '/src/CdliTwoStageSignup/Validator/AssertNoValidationInProgress.php',
    'CdliTwoStageSignup\Form\EmailVerification'                 => __DIR__ . '/src/CdliTwoStageSignup/Form/EmailVerification.php',
);