<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliTwoStageSignupTest\ServiceConfigurationTest'                   => __DIR__ . '/tests/CdliTwoStageSignupTest/ServiceConfigurationTest.php',
    'CdliTwoStageSignupTest\Service\EmailVerificationTest'              => __DIR__ . '/tests/CdliTwoStageSignupTest/Service/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Mapper\EmailVerificationTest'               => __DIR__ . '/tests/CdliTwoStageSignupTest/Mapper/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Validator\AssertNoValidationInProgressTest' => __DIR__ . '/tests/CdliTwoStageSignupTest/Validator/AssertNoValidationInProgressTest.php',
    'CdliTwoStageSignupTest\Entity\EmailVerificationTest'               => __DIR__ . '/tests/CdliTwoStageSignupTest/Entity/EmailVerificationTest.php',
    'CdliTwoStageSignupTest\Framework\TestCaseOptions'                  => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/TestCaseOptions.php',
    'CdliTwoStageSignupTest\Framework\TestCase'                         => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/TestCase.php',
    'CdliTwoStageSignupTest\Framework\MapperTestCase'                   => __DIR__ . '/tests/CdliTwoStageSignupTest/Framework/MapperTestCase.php',
    'CdliTwoStageSignup\Module'                                         => __DIR__ . '/Module.php',
    'CdliTwoStageSignup\Controller\RegisterController'                  => __DIR__ . '/src/CdliTwoStageSignup/Controller/RegisterController.php',
    'CdliTwoStageSignup\Service\EmailVerification'                      => __DIR__ . '/src/CdliTwoStageSignup/Service/EmailVerification.php',
    'CdliTwoStageSignup\Mapper\EmailVerificationHydrator'               => __DIR__ . '/src/CdliTwoStageSignup/Mapper/EmailVerificationHydrator.php',
    'CdliTwoStageSignup\Mapper\EmailVerification\MapperInterface'       => __DIR__ . '/src/CdliTwoStageSignup/Mapper/EmailVerification/MapperInterface.php',
    'CdliTwoStageSignup\Mapper\EmailVerification\ZendDb'                => __DIR__ . '/src/CdliTwoStageSignup/Mapper/EmailVerification/ZendDb.php',
    'CdliTwoStageSignup\Options\ModuleOptions'                          => __DIR__ . '/src/CdliTwoStageSignup/Options/ModuleOptions.php',
    'CdliTwoStageSignup\Options\EmailOptionsInterface'                  => __DIR__ . '/src/CdliTwoStageSignup/Options/EmailOptionsInterface.php',
    'CdliTwoStageSignup\Validator\AssertNoValidationInProgress'         => __DIR__ . '/src/CdliTwoStageSignup/Validator/AssertNoValidationInProgress.php',
    'CdliTwoStageSignup\Entity\EmailVerification'                       => __DIR__ . '/src/CdliTwoStageSignup/Entity/EmailVerification.php',
    'CdliTwoStageSignup\Form\EmailVerification'                         => __DIR__ . '/src/CdliTwoStageSignup/Form/EmailVerification.php',
    'CdliTwoStageSignup\Form\EmailVerificationFilter'                   => __DIR__ . '/src/CdliTwoStageSignup/Form/EmailVerificationFilter.php',
);